# Generated by Django 5.2.7 on 2025-10-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=80)),
                ('reaction_level', models.FloatField()),
                ('coping_action', models.CharField(max_length=5000)),
                ('effectiveness', models.FloatField()),
            ],
        ),
    ]
