# Generated by Django 5.2.7 on 2025-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_in',
            name='day_type',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='check_in',
            name='relaxed_today',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
